# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imageDisp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantomogramInfo',
            fields=[
                ('image_name_text', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('present_teeth_text', models.CharField(max_length=32)),
                ('input_image', models.ImageField(upload_to='Images')),
                ('output_image', models.ImageField(upload_to='OutputImages')),
                ('thresh_image', models.ImageField(upload_to='ThreshImages')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ToothInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x1', models.IntegerField()),
                ('start_y1', models.IntegerField()),
                ('start_x2', models.IntegerField()),
                ('start_y2', models.IntegerField()),
                ('is_present', models.BooleanField()),
                ('teeth_image', models.ImageField(upload_to='TeethImages')),
                ('teeth_id', models.CharField(max_length=3, validators=[imageDisp.models.validate_tooth_name])),
                ('pantomogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageDisp.PantomogramInfo')),
            ],
        ),
    ]
