# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import imageDisp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantomogramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name_text', models.CharField(max_length=200)),
                ('present_teeth_text', models.CharField(max_length=32)),
                ('input_image', models.ImageField(upload_to="Images")),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
