# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageDisp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pantomograminfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='pantomograminfo',
            name='image_name_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
