# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageDisp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantomograminfo',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='toothinfo',
            name='teeth_image',
            field=models.ImageField(null=True, upload_to='TeethImages'),
        ),
    ]
