# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageDisp', '0002_auto_20170723_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantomograminfo',
            name='b_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pantomograminfo',
            name='process_image_gap',
            field=models.ImageField(null=True, upload_to='ProcessImages'),
        ),
        migrations.AddField(
            model_name='pantomograminfo',
            name='process_image_laplace',
            field=models.ImageField(null=True, upload_to='ProcessImages'),
        ),
        migrations.AddField(
            model_name='pantomograminfo',
            name='process_image_starting_points',
            field=models.ImageField(null=True, upload_to='ProcessImages'),
        ),
    ]
